version: "3"

services:
  authserver:
    build:
      context: ./authserver
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "1337:1337"
  cache:
    image: "redis:latest"
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
