name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Install dependencies
        run: go mod tidy
        working-directory: ./cli

      - name: Build
        run: go build -v ./...
        working-directory: ./cli

      - name: Test
        run: go test ./...
        working-directory: ./cli
